In [2]:
import numpy as np

In [3]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element
for i in a:
    print(f'a[{i}]: {a[i]}')

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [ ]:
# Check numpy version
print(np.__version__)

2.1.3


In [ ]:
# Check the type of the array
type(a)

numpy.ndarray

In [8]:
# Check the type of values store in the numpy array
a.dtype

dtype('int64')

In [9]:
# Checking type and Value type for the below array
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
type(b)

numpy.ndarray

In [10]:
b.dtype

dtype('float64')

In [11]:
# Create a numpy array
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [12]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [13]:
# Assign the 5th element to 0
c[4] = 0
c

array([100,   1,   2,   3,   0])

In [14]:
# 'Try yourself' - Assign the array
a = np.array([10, 2, 30, 40, 50])
a[1] = 20
a

array([10, 20, 30, 40, 50])

In [15]:
# Slicing numpy array
d = c[1:4]
d

array([1, 2, 3])

In [16]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [17]:
d

array([  1,   2, 300])

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [21]:
print(arr[:4])

[1 2 3 4]


In [22]:
print(arr[4:])

[5 6 7]


In [23]:
print(arr[1:5:])

[2 3 4 5]


In [24]:
# alt to above
print(arr[1:5])

[2 3 4 5]


In [25]:
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [26]:
d = c[select]
d

array([100,   2, 300, 400])

In [27]:
c

array([100,   1,   2, 300, 400])

In [28]:
c[select] = 100000

In [29]:
c

array([100000,      1, 100000, 100000, 100000])

In [30]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [31]:
a.size

5

In [33]:
# Number of dimensions
a.ndim

1

In [34]:
a.shape

(5,)

In [36]:
a = np.array([1, -1, 1, -1])
mean = a.mean()
mean

np.float64(0.0)

In [38]:
standard_deviation = a.std()
standard_deviation

np.float64(1.0)

In [39]:
a.max()

np.int64(1)

In [41]:
a.min()

np.int64(-1)

In [42]:
c = np.array([-10, 201, 43, 94, 502])
c.sum()

np.int64(830)

In [44]:
sum = 0
for i in c:
    sum += i
sum

np.int64(830)

In [46]:
a=np.array([-1,1]) 

b=np.array([1,1]) 

np.dot(a,b) 

np.int64(0)

In [49]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
X

array([[1, 0, 1],
       [2, 2, 2]])

In [50]:
out

array([1, 2])

In [51]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[0,1],[1,0]]) 

Z=X+Y 

In [52]:
Z

array([[1, 1],
       [1, 1]])

In [53]:
a=np.array([0,1]) 

b=np.array([1,0]) 

np.dot(a,b) 

np.int64(0)